name: weekly update

on:
  push:
    branches: [ main ]
  #pull_request:
    #branches: [ main ]
  schedule:
    # - cron: '*/5 * * * *'
    # 表达式生成  https://crontab.guru/
    # 此处是UTC时间 即北京时间 -8小时
    - cron: '40 2,12 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib pandas openpyxl
    - name: Setup chinese fonts
      run:
        sudo apt-get install fonts-wqy-zenhei
        
        sudo fc-cache -f -v
       
    - name: Run
      run: |
        python invest.py

    - name: commit
      run: |
         git config --local user.email "sungsun@163.com"
         git config --local user.name "sungang"
         git add invest_report.png
         git add invest_output.xlsx
         git commit -m "更新数据"
    - name: push
      uses:  ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUBTOKEN }}
         branch: main
